# Header
menu:
  Home: /
  Archives: /archives
  About: /about

rss: /atom.xml

social:
  github: https://github.com/itkoren
  linkedin: https://il.linkedin.com/in/itkoren
  twitter: https://twitter.com/itkoren


# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- twitter

widget_twitter:
  custom: true
  href: https://twitter.com/itkoren
  id: 521047775308312576

# Miscellaneous
google_analytics:
favicon: /favicon.png
google_plus:
fb_admins:
fb_app_id:
twitter: itkoren
github: itkoren